version: "3.9"

networks:
  fastfood-fiap-network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_USERNAME: admin
      MONGO_INITDB_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/mongo:/data/db
    networks:
      - fastfood-fiap-network

  fastfood-fiap-api:
    image: fastfood-fiap-api
    command: ["java", "-jar", "api.jar"]
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mongo
    depends_on:
      - mongo
    networks:
      - fastfood-fiap-network
  #    deploy:
  #      replicas: 2