apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-fiap-deployment
spec:
  selector:
    matchLabels:
      app: fastfood-fiap
  replicas: 2
  template:
    metadata:
      labels:
        app: fastfood-fiap
    spec:
      containers:
        - name: fastfood-fiap-api
          image: ghbalbuquerque/fastfood-fiap-api:latest
          env:
            - name: DB_HOST
              value: mongodb-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fastfood-fiap-service
spec:
  type: NodePort
  selector:
    app: fastfood-fiap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


