apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-fiap-deployment
  namespace: fiap-pos-tech
spec:
  selector:
    matchLabels:
      app: fastfood-fiap
  replicas: 1
  template:
    metadata:
      labels:
        app: fastfood-fiap
    spec:
      containers:
        - name: fastfood-fiap-api
          image: ghbalbuquerque/fastfood-fiap-api:latest
          resources:
            requests:
              cpu: "200m"  # Requisição de CPU inicial
              memory: "512Mi"
            limits:
              cpu: "500m"  # Limite de CPU
              memory: "1Gi"
          env:
            - name: DB_HOST
              value: mongodb-service
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: Check-Health-Header
                  value: "application-up"
            initialDelaySeconds: 7
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fastfood-fiap-service
  namespace: fiap-pos-tech
spec:
  type: LoadBalancer
  selector:
    app: fastfood-fiap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080



