apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
  mongo-init.js: |
    db = db.getSiblingDB('db-fiap-fastfood');

    db.createUser(
        {
            user: "admin",
            pwd: "password",
            roles: [
                {
                    role: "readWrite",
                    db: "db-fiap-fastfood"
                }
            ]
        }
    )

    db.createCollection("Attendant");
    db.createCollection("Client");
    db.createCollection("Order");
    db.createCollection("Product");
    db.createCollection("Payment");
    db.createCollection("Checkout");